export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_SUCCESS';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';

export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS'; 
